version: '3'

services:
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgres-data:
