openapi: 3.1.0
info:
  title: DatariskScore
  description: A service for storing and retrieving credit scores
  version: 0.1.0
paths:
  /score:
    post:
      summary: Create score
      description: Submits a new CPF. The score for that CPF is computed and stored
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cpf:
                  $ref: "#/components/schemas/cpf"
      responses:
        "201":
          description: Score successfully created
        "400":
          description: Invalid input body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorObject"
        "419":
          description: There was already a score stored for the input CPF
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorObject"
        "500":
          description: Some error happened on the server. For example, the database might be down
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorObject"
  /score/{cpf}:
    parameters:
      - name: cpf
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/cpf"
    get:
      responses:
        "200":
          description: Returns the score for the input CPF
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/scoreResponse"
        "404":
          description: There is no score for the input CPF
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorObject"
        "500":
          description: Some error happened on the server. For example, the database might be down
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorObject"
components:
  schemas:
    cpf:
      type: string
    errorObject:
      type: object
      properties:
        error:
          type: string
    scoreResponse:
      type: object
      properties:
        score:
          type: integer
          minimum: 1
          maximum: 1000
        created_at:
          type: string
          format: date-time
